workflows:
  android-release:
    name: Royal Chess Android Release
    max_build_duration: 120
    instance_type: linux  # <-- غيرتها من mac_mini_m2 ل linux

    environment:
      flutter: 3.24.0
      java: 17

    scripts:
      - name: Verify Flutter version
        script: |
          set -e
          flutter --version
          test "$(flutter --version | sed -n '1p' | awk '{print $2}')" = "3.24.0"

      - name: Check android folder exists
        script: ls -la android/gradle/wrapper/  # <-- ضفت ده عشان نتأكد

      - name: Prepare Flutter SDK path
        script: |
          set -e
          echo "flutter.sdk=$FLUTTER_ROOT" > "$CM_BUILD_DIR/android/local.properties"

      - name: Get Flutter packages
        script: |
          set -e
          flutter pub get

      - name: Build APK Release
        script: |
          set -e
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
